[bans]
multiple-versions = "deny"
wildcards         = "deny"

[advisories]
db-path       = "~/.cargo/advisory-db"
db-urls       = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained  = "warn"
yanked        = "deny"

[licenses]
allow     = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-DFS-2016", "OpenSSL"]
deny      = ["GPL-2.0", "GPL-3.0", "AGPL-3.0", "LGPL-2.0", "LGPL-3.0"]
copyleft  = "warn"

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-registry   = ["https://github.com/rust-lang/crates.io-index"]
